CREATE PROCEDURE PRIORIDADE_INSERIR
(
@PRI_Codigo VARCHAR(50),
@PRI_Descricao VARCHAR(100),
@PRI_CorTag VARCHAR(9),
@PRI_Ordem INT
)
AS
BEGIN
UPDATE PRIORIDADE SET PRI_Ordem = PRI_Ordem + 1 WHERE PRI_Ordem >= @PRI_Ordem
INSERT INTO PRIORIDADE (PRI_Codigo,PRI_CorTag,PRI_Descricao,PRI_Ordem)
VALUES (@PRI_Codigo,@PRI_CorTag,@PRI_Descricao,@PRI_Ordem)
SELECT @@IDENTITY
END